runtime: python310
default_expiration: "365d"
app_engine_apis: true

# Slack has a very short timeout on API callbacks, so we need to keep at least 1
# process running for it
automatic_scaling:
  min_instances: 1

# min_instances requires warmup requests to work
inbound_services:
  - warmup

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  mime_type: image/x-icon
  upload: static/favicon.ico

- url: /admin/.*
  script: auto
  login: admin
  secure: always

- url: /.*
  script: auto
  secure: always

builtins:
- remote_api: on
