runtime: python27
threadsafe: yes
api_version: 1
default_expiration: "365d"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  mime_type: image/x-icon
  upload: static/favicon.ico

- url: /admin/.*
  script: snippets.application
  login: admin

- url: .*
  script: snippets.application

skip_files:
- .git
- .DS_Store
- .*.pyc

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
# This also brings in webapp2_extras:
- name: webapp2
  version: "2.5.2"
