application: weekly-snippets-hrd
version: 1
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: "365d"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /images/favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /admin/.*
  script: snippets.application
  login: admin

- url: .*
  script: snippets.application

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
# This also brings in webapp2_extras:
- name: webapp2
  version: "2.5.1"
