runtime: python310
default_expiration: "365d"
app_engine_apis: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  mime_type: image/x-icon
  upload: static/favicon.ico

- url: /admin/.*
  script: auto
  login: admin
  secure: always

- url: /.*
  script: auto
  secure: always

builtins:
- remote_api: on
